# THIS DOCKER FILE BUILDS ON TOP OF ALPINE BASE IMAGE AND THEN DOWNLOAD AND BUILD NGINX SERVER FROM SCRATCH
FROM alpine:latest

ARG VERSION=1.12.0

# RUN set -x shell command is used to log the execution process of the RUN command. Helps to troubleshoot
# apk is the Alpine's package manager tool.
RUN set -x                                 && \
    apk add --no-cache --virtual .build-deps  \
        build-base                            \
        gnupg                                 \
        pcre-dev                              \
        wget                                  \
        zlib-dev                           && \  
                                              \ 
# Retrieve, verify and unpack Nginx source    \
    TMP="$(mktemp -d)" && cd "$TMP"        && \
    gpg --keyserver pgp.mit.edu --recv-keys \
        B0F4253373F8F6F510D42178520A9993A1C052F8  && \
    wget -q http://nginx.org/download/nginx-${VERSION}.tar.gz && \
    wget -q http://nginx.org/download/nginx-${VERSION}.tar.gz.asc && \
    gpg --verify nginx-${VERSION}.tar.gz.asc  && \
    tar -xf nginx-${VERSION}.tar.gz && \
                                       \
# Build and install nginx               \
    cd nginx-${VERSION} && \
    ./configure            \
        --with-ld-opt="-static" \
        --with-http_sub_module  && \
    make install  && \
    strip /usr/local/nginx/sbin/nginx && \
                                     \ 
#Clean up                            \
    cd / && rm -rf "$TMP" && \
    apk del .build-deps && \
                           \
# Symlink access and error logs to /dev/stdout and /dev/stderr , \
# in order to make use of docker's logging mechanism \
    ln -sf /dev/stdout /usr/local/nginx/logs/access.log && \
    ln -sf /dev/stderr /usr/local/nginx/logs/error.log

# Customize static content and configuration
#COPY index.html /usr/local/nginx/html/
#COPY nginx.conf /usr/local/nginx/conf/

# Change default stop signal from SIGTERM to SIGQUIT
STOPSIGNAL SIGQUIT

# Export port
EXPOSE 80

# Define entrypoint and default params
ENTRYPOINT [ "/usr/local/nginx/sbin/nginx" ]
CMD [ "-g", "daemon off;" ]




